update versions for 'numpy', 'dask', 'click', 'pandas'
locked 'dask==2024.8.0'
AttributeError: module 'dask' has no attribute 'bag'

locked click==8.1.8 because of error CliRunner(mix_stderr=False) in Py3.9

use different 'numpy' versions to support Python versions 3.9-3.13