Upgrade CI to Python 3.8
Because:

    ImportError: Error importing plugin "spinta.testing.pytest": cannot
    import name 'TypedDict' from 'typing'
    (/usr/local/lib/python3.7/typing.py)

https://gitlab.com/atviriduomenys/spinta/-/jobs/919266278

I checked what is on production, both instances use Python 3.8 already.